name: Build and deploy Django app to Azure Web App - LSTMstockpredictor

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for Python apps

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the version of Python you're working with

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: .

  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for deployment
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Use the publish profile for login

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LSTMstockpredictor'
          package: .

          
